config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'home/index'
  get 'home/external', as: :external_root

  root "home#index"

  get '/searches/poll', to: 'searches#poll', as: :run_listings_poll
  resources :listings_polls


  resources :listings
  resources :searches
  resources :users

  get '/login', to: 'user_sessions#new', as: :new_user_session
  post '/login', to: 'user_sessions#create', as: :login
  delete '/logout', to: 'user_sessions#destroy', as: :logout


end

app/models/listings_poll.rb
# == Schema Information
#
# Table name: listings_polls
#
#  id           :integer          not null, primary key
#  finished_at  :datetime
#  is_automated :boolean
#  notes        :text
#  started_at   :datetime
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class ListingsPoll < ApplicationRecord
  has_many :listings

  RESULTS_PER_PAGE = 24

  def self.run
    new_poll = self.create(started_at: Time.now)
    Search.all.each do |search|
      new_poll.get_listings_for(search)
    end

    new_poll.finished_at = Time.now
    new_poll.save
  end

  def get_listings_for(a_search)
    @search = a_search

    run_search
    collect_listings
  end

  def run_search
    params = {
      keyword: @search.keywords,
      city: '',
      miles: 25,
      sort: 0,
      priceFrom: '',
      priceTo: '',
      state: '',
      zip: '',
      perPage: RESULTS_PER_PAGE
    }

    # a valid GET request url from the browser
    # example url...
    # https://classifieds.ksl.com/search/?keyword=anvil&zip=&miles=25&priceFrom=&priceTo=&marketType[]=Sale&city=&state=&sort=0
    query_params = URI::QueryParams.dump(params)
    full_url = 'https://classifieds.ksl.com/search/?' + query_params
    log("About to GET: #{full_url}")

    options = Selenium::WebDriver::Chrome::Options.new(args: ['headless'])
    @results_page = Selenium::WebDriver.for(:chrome, options: options)
    @results_page.get(full_url)
  end

  def collect_listings
    listings = @results_page.find_elements(:css, '.listing-item')
    log("Found #{listings.count} listings.")
    
    listings.each do |l|
      title       = l.find_element(class: 'item-info-title-link').attribute('innerHTML')
      description = l.find_element(class: 'item-description').attribute('innerHTML')
      pricing     = l.find_element(class: 'item-info-price').attribute('innerHTML')
      url         = l.find_element(class: 'listing-item-link').attribute('href')

      # description still has some html and other tags in it
      description.gsub!(/<!-- react-text: \d+ -->/, '')
      description.gsub!(/<!-- \/react-text -->/, '')
      description.gsub!(/<div .+\/div>/, '')

      # convert the currency string to a float if possible
      if /^\$(\d{1,3},?)+\.\d\d$/.match(pricing)
        price = pricing.scan(/[.0-9]/).join.to_f
      else
        price = ''
      end

      @search.listings << self.listings.create(
        title: title,
        description: description,
        pricing: pricing,
        price: price,
        url: url,
        listings_poll_id: self.id
      )
      log("Raw listing: #{l}")
    end
  end


  def log(msg)
    self.update_attribute(:notes,  "#{notes}\n#{msg}")
  end

end

app/controllers/listings_polls_controller.rb
class ListingsPollsController < ApplicationController
  before_action :set_listings_poll, only: [:show, :edit, :update, :destroy]

  # GET /listings_polls
  # GET /listings_polls.json
  def index
    @listings_polls = ListingsPoll.all
  end

  # GET /listings_polls/1
  # GET /listings_polls/1.json
  def show
  end

  # GET /listings_polls/new
  def new
    @listings_poll = ListingsPoll.new
  end

  # GET /listings_polls/1/edit
  def edit
  end

  # POST /listings_polls
  # POST /listings_polls.json
  def create
    @listings_poll = ListingsPoll.new(listings_poll_params)

    respond_to do |format|
      if @listings_poll.save
        format.html { redirect_to @listings_poll, notice: 'Listings poll was successfully created.' }
        format.json { render :show, status: :created, location: @listings_poll }
      else
        format.html { render :new }
        format.json { render json: @listings_poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings_polls/1
  # PATCH/PUT /listings_polls/1.json
  def update
    respond_to do |format|
      if @listings_poll.update(listings_poll_params)
        format.html { redirect_to @listings_poll, notice: 'Listings poll was successfully updated.' }
        format.json { render :show, status: :ok, location: @listings_poll }
      else
        format.html { render :edit }
        format.json { render json: @listings_poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings_polls/1
  # DELETE /listings_polls/1.json
  def destroy
    @listings_poll.destroy
    respond_to do |format|
      format.html { redirect_to listings_polls_url, notice: 'Listings poll was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listings_poll
      @listings_poll = ListingsPoll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listings_poll_params
      params.require(:listings_poll).permit(:is_automated, :started_at, :finished_at, :notes)
    end
end

app/helpers/listings_polls_helper.rb
module ListingsPollsHelper
end

app/views/listings_polls/_form.html.erb
<%= form_with(model: listings_poll, local: true) do |form| %>
  <% if listings_poll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listings_poll.errors.count, "error") %> prohibited this listings_poll from being saved:</h2>

      <ul>
      <% listings_poll.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :is_automated %>
    <%= form.check_box :is_automated %>
  </div>

  <div class="field">
    <%= form.label :started_at %>
    <%= form.datetime_select :started_at %>
  </div>

  <div class="field">
    <%= form.label :finished_at %>
    <%= form.datetime_select :finished_at %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/listings_polls/edit.html.erb
<h1>Editing Listings Poll</h1>

<%= render 'form', listings_poll: @listings_poll %>

<%= link_to 'Show', @listings_poll %> |
<%= link_to 'Back', listings_polls_path %>

app/views/listings_polls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listings Polls</h1>

<table>
  <thead>
    <tr>
      <th>Is automated</th>
      <th>Started at</th>
      <th>Finished at</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings_polls.each do |listings_poll| %>
      <tr>
        <td><%= listings_poll.is_automated %></td>
        <td><%= listings_poll.started_at %></td>
        <td><%= listings_poll.finished_at %></td>
        <td><%= listings_poll.notes %></td>
        <td><%= link_to 'Show', listings_poll %></td>
        <td><%= link_to 'Edit', edit_listings_poll_path(listings_poll) %></td>
        <td><%= link_to 'Destroy', listings_poll, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listings Poll', new_listings_poll_path %>

app/views/listings_polls/new.html.erb
<h1>New Listings Poll</h1>

<%= render 'form', listings_poll: @listings_poll %>

<%= link_to 'Back', listings_polls_path %>

app/views/listings_polls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Is automated:</strong>
  <%= @listings_poll.is_automated %>
</p>

<p>
  <strong>Started at:</strong>
  <%= @listings_poll.started_at %>
</p>

<p>
  <strong>Finished at:</strong>
  <%= @listings_poll.finished_at %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @listings_poll.notes %>
</p>

<%= link_to 'Edit', edit_listings_poll_path(@listings_poll) %> |
<%= link_to 'Back', listings_polls_path %>