config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'home/index'
  get 'home/external', as: :external_root

  root "home#index"

  get '/searches/poll', to: 'searches#poll', as: :run_listings_poll
  resources :listings_polls


  resources :listings
  resources :searches
  resources :users

  get '/login', to: 'user_sessions#new', as: :new_user_session
  post '/login', to: 'user_sessions#create', as: :login
  delete '/logout', to: 'user_sessions#destroy', as: :logout


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :must_be_logged_in, only: [:external]

  def index
  end

  def external
  end
end

app/helpers/home_helper.rb
module HomeHelper

  def listings_not_reviewed_count
    current_user.not_reviewed_listings.count
  end

end

app/views/home/external.html.erb
<h1>KSLWatcher</h1>
<div id='intro' class='nice-box'>
  <p class='nice-box-header'>
    Welcome to the KSLWatcher!
  </p>
  <p>
    This service will keep an eye on the KSL Classifieds for you and alert
    you when a new listing of interest appears.  Using this system means:
      <ul>
        <li>
          More free time -- no longer do you need to visit KSL regularly to check for that unopened BeeGees vinyl record you've been pining after.
        </li>
        <li>
          Fewer lost opportunities -- don't lose out to someone who's spending all their time scanning the KSL site while you do real work in the real world.
        </li>
      </ul>
  </p>
</div>
<div id='signup-pitch' class='nice-box'>
  Sign up to be a user.  We'll let you know as soon as the service goes live.
  <%= link_to "Register", new_user_path, class: 'btn btn-default' %>
</div>
<div id='signup-pitch' class='nice-box'>
  Already signed up?  <%= link_to "Login", new_user_session_path, class: 'btn btn-default' %>
</div>

app/views/home/index.html.erb
<h1>KSLWatcher</h1>
<div id='intro' class='nice-box'>
  <p class='nice-box-header'>
    Welcome to the KSLWatcher!
  </p>

  <% if current_user.has_new_listings? %>
    <div class='good-news-box'>
      You have <%= link_to "#{listings_not_reviewed_count} new listings!", listings_path(show_filter: :not_reviewed) %>
    </div>
  <% end %>

<div id='other-links' class='nice-box'>
  <%= link_to "Searches", searches_url, class: 'btn btn-default' %>
  <%= link_to "Listings", listings_path, class: 'btn btn-default' %>
  <%= link_to 'Run Searches on KSL', run_listings_poll_path, remote: true, class: 'btn btn-default' %>
</div>